### PR TITLE
Dramatically update Makefile

### PR DESCRIPTION
**Pull request by HalosGhost**
- Out-of-Tree builds (defaults to ./build, configurable via DIST)
- Install and uninstall rules (which respect DESTDIR and PREFIX)
- Production of static and dynamic libraries
- Testing of all three methods of inclusion
    - direct file inclusion
    - static library
    - dynamic library (using LD_LIBRARY_PATH)
- Better declaration of PHONY targets
- Expose ability to override CC and CFLAGS

### CODE REVIEW

**Comment by orangeduck** [comment]
Thanks for reminding me of this I will check it out this weekend :)

**Comment by HalosGhost** [comment]
@jflopezfernandez, I appreciate the kind words and suggestions. I have made your suggested changes. Anything else you think should be updated?

**Comment by orangeduck** [comment]
I'm getting this error on windows using MinGW64: `mpc.c:1:0: error: -fPIC ignored for target (all code is position independent)`. Removing the `-fPIC` flag fixes it - I think this flag isn't required on windows (with MinGW). Also I noticed that the install command wont work properly on windows - although this isn't a massive deal since the location of installed libraries on windows is not always clear.

Do you think you'd be able to test and update the Makefile on windows? I don't mind if it isn't full featured but it would be nice to make sure it works "out of the box".

Thanks again!

Dan

**Comment by HalosGhost** [comment]
I don't have access to a Windows machine to test on easily. But, I can definitely make some changes to make it more windows friendly! Will do in the next few days!

**Comment by XVilka** [comment]
You can setup AppVeyor or Azure Pipelines CI to test/check the code on Windows platforms. Both are free for FOSS.

**Comment by HalosGhost** [comment]
@XVilka, thank you for letting me know, but my preference is to not use any Microsoft service if I can help it.

In this case, I can just add a platform variable, and trigger based on that. Not much of an issue :)

**Comment by HalosGhost** [comment]
@orangeduck, hypothetically, this most-recent version of the `Makefile` should conditionally call `-fPIC` only on not-cygwin.

Does this properly solve the issue for you?

**Comment by orangeduck** [comment]
Hi @HalosGhost,

Thanks that fixes it on cygwin, although the problem still exists when using MinGW. You can see an example of a makefile which I made which supports windows platforms here: https://github.com/orangeduck/Cello/blob/master/Makefile

I don't claim to be an expert at makefiles but it might help you see what needs to be done for windows based platforms.

Thanks again,

Dan

**Comment by HalosGhost** [comment]
Ahh, I see. So, to clarify, `-fPIC` shouldn't be added on any of the Win platforms? MSYS/mingw/cygwin/Windows?

**Comment by orangeduck** [comment]
Correct 👍

**Comment by HalosGhost** [comment]
Cheers. I will get it done momentarily.

**Comment by jflopezfernandez** [comment]
@HalosGhost Hey, sorry man, sorry I didn't reply until now, I didn't get a notification about replies here at all. Refactoring `mkdir` into a variable to make it more robust across systems was it, as far as my feedback was concerned. It really is a great Makefile, props again.

That's a really interesting point about `-fPIC` on Windows, though, I didn't know that either.

**Comment by HalosGhost** [comment]
@jflopezfernandez, not a problem at all.

Okay. @orangeduck, from what I can tell, Cygwin, MSYS, Mingw, and Windows all have `$(OS)` set to `Windows_NT`, and this `Makefile` (in its current state), does not need to differentiate them. So, for now, I believe just detecting that variable is enough. If it becomes needed, I believe I have stumbled on another person's strategy for differentiating them.

Let me know if this does not work for you at all or if you have suggestions.

**Comment by orangeduck** [comment]
works perfectly, thanks!

**Pull request merged**
