### PR TITLE
Tree Traversal

### PR DESCRIPTION
**Pull request by petermlm**
Like I've discussed in #49, the tree traversal functionality is implemented.

I've added things to the traversal example. The terminal output isn't much to look at. (I may make a few better commits regarding that) but the code should be clear in terms of functionality.

### CODE REVIEW

**Comment by orangeduck** [comment]
Hi Peter,

I had a quick look over. Looks great.

I noticed that the traversal was doing some memory allocation with the heap using `malloc`. Is it not possible to avoid this memory allocation by storing the traversal structures on the stack? I guess this might not be possible without storing a parent pointer in the `ast`.

Usually when you call a function which returns an allocated object (on the heap) it is your responsibility to delete it when finished - but these functions (as far as I can tell) have a weird interface where the structure is freed once the traversal is complete.

What if I want to allocated a traversal structure but for whatever reason don't actually want to traverse it?

- Dan

**Comment by petermlm** [comment]
Hello.

Good points.

> I guess this might not be possible without storing a parent pointer in the ast.

Even with a parent pointer you would need to keep state for each iteration step. At each node, depending on the traversal order (pre or post), the `next` function needs to know where to go. For example, suppose the following tree:

```
    a
 / / \ \
x y  z  w
```

So, it's a tree with a root `a`, and children `x`, `y`, `z`, and `w`.

In pre-oder, when we are at `x`, the traversal structure knows that this is the last node "going down" and that it's parent is `a`. Using this information is knows to go to `y` when `next` is called. When in `y` it knows it should go to `z` next, and so on.

All this information is needed and it is dynamic, depending on the size of the AST. So it doesn't seem possible to store it on the stack.

Also, the traversal structure is something you want to give to te user so he can manipulate it however he wants by calling the `next` function. He might just want to search for something in which case he would go through the whole thing by calling `next` until he finds what he wants, or he will want to do some sort of analysis over it and therefore do lots of function calls passing the structure as a parameter.

> Usually when you call a function which returns an allocated object (on the heap) it is your responsibility to delete it when finished

Yes, this is true. For these functions you would have to call `next` until there is nothing more to traverse so the free function may be called. This is bad. For example, if you just want to search for something in the tree with 100 nodes and find it in the 5th node, then you would still have to go through 95 nodes in order to free the memory. This is stupid indeed...

We could implement a free function to free the traversal structure. This would make sense and is very common design pattern.

I could add that. What do you think?

**Comment by orangeduck** [comment]
Makes sense about the heap allocation. I guess I was thinking about the special case of a binary tree, which I think should be possible to traverse without any dynamic memory allocation.

Yeah I think having a user function to free the traversal structure makes more sense.

**Comment by petermlm** [comment]
Yes, with a binary tree it is possible to traverse with with keeping a "history", it is an interesting particular case of this situation.

Ok, so I'll work on the free later this week. Maybe on Thursday.

**Comment by petermlm** [comment]
Hello.

I've push the traversal free.

**Comment by orangeduck** [comment]
Thanks :+1:

**Pull request merged**
